apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
type: Opaque
stringData:
  django-secret-key: "your-django-secret-key-here"
  postgres-user: "postgres"
  postgres-password: "your-secure-password-here" 